import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header/Header";
import Sidebar from "./components/Sidebar/Sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-cols-12">
          {/* Sidebar */}
          <aside className="col-span-3 bg-gray-100">
            <Sidebar></Sidebar>
          </aside>
          {/* Main Section */}
          <div className="col-span-9">
            <header>
              <Header></Header>
            </header>
            <main className="min-h-[calc(120vh-232px)]">
              {/* Main Section Dynamic */}
              <section className="col-span-9">
                {children}
              </section>
            </main>
            <footer className="footer footer-center bg-base-300 text-base-content p-4">
              <aside>
                <p>Copyright © {new Date().getFullYear()} - All right reserved by ACME Industries Ltd</p>
              </aside>
            </footer>
          </div>
        </div>
      </body>
    </html>
  );
}
